name: Node.js Package

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install nodejs dependencies
        run: sudo apt-get install gpg dirmngr

      - name: Read .tool-versions
        uses: marocchino/tool-versions-action@v1
        id: versions

      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ steps.versions.outputs.nodejs}}

      - name: Install dependencies
        run: yarn install

      - name: Publish the package to npmjs
        run: |
          npm config set //registry.npmjs.org/:_authToken=$NODE_AUTH_TOKEN
          npm config set @oddcamp:registry https://registry.npmjs.org/
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}

      - name: Publish the package to GPR
        run: |
          npm config set //npm.pkg.github.com/:_authToken=$NODE_AUTH_TOKEN
          npm config set @oddcamp:registry https://npm.pkg.github.com/
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
